package autogeneratedProyect;

public class Dado {
	private int _cara;
	public JuegoDados _unnamed_JuegoDados_;

	public Dado() {
		throw new UnsupportedOperationException();
	}

	public void lanzar() {
		throw new UnsupportedOperationException();
	}

	public short getCara() {
		throw new UnsupportedOperationException();
	}
}