package autogeneratedProyect;

public class JuegoDados {
	private int _resultado;
	private Dado _dado1;
	private Dado _dado2;
	public Menu _unnamed_Menu_;
	public Dado _unnamed_Dado_;

	public JuegoDados() {
		throw new UnsupportedOperationException();
	}

	public void lanzarDados() {
		throw new UnsupportedOperationException();
	}

	public void mostrarResultado() {
		throw new UnsupportedOperationException();
	}

	public boolean esVictoria() {
		throw new UnsupportedOperationException();
	}

	public int getResultado() {
		return this._resultado;
	}
}