package autogeneratedProyect;

import java.util.Scanner;

public class Menu {
	private Scanner _scanner;
	private int _opcion;
	private JuegoDados _juego;
	public JuegoDados _unnamed_JuegoDados_;

	public Menu() {
		throw new UnsupportedOperationException();
	}

	private int pedirOpcion() {
		throw new UnsupportedOperationException();
	}

	private void mostrarMenu() {
		throw new UnsupportedOperationException();
	}

	private void jugar() {
		throw new UnsupportedOperationException();
	}

	private void salir() {
		throw new UnsupportedOperationException();
	}

	private void opcionIvalida() {
		throw new UnsupportedOperationException();
	}

	private void limpiarPantalla() {
		throw new UnsupportedOperationException();
	}

	public void mainloop() {
		throw new UnsupportedOperationException();
	}
}